# Generated by Django 5.2.5 on 2025-08-28 22:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
